# Generated by Django 4.0.5 on 2022-06-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_autor_post_alter_post_categoria_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagem_post',
            new_name='foto',
        ),
    ]
