# Generated by Django 4.0.5 on 2022-06-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_foto_post_imagem_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagem_foto',
            new_name='imagem_post',
        ),
    ]
