# Generated by Django 4.0.5 on 2022-06-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_imagem_foto_post_imagem_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagem_post',
            new_name='foto',
        ),
        migrations.AddField(
            model_name='post',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='post_imagens_principal/%Y/%m/%d', verbose_name='Imagem Principal'),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo_principal_post',
            field=models.CharField(default=1, max_length=255, verbose_name='Título Principal'),
            preserve_default=False,
        ),
    ]
