# Generated by Django 4.0.5 on 2022-06-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_imagem_post_post_foto_post_foto_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal_post', models.CharField(max_length=255, verbose_name='Título Principal')),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='post_imagens_principal/%Y/%m/%d', verbose_name='Imagem Principal')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='foto_principal',
        ),
        migrations.RemoveField(
            model_name='post',
            name='titulo_principal_post',
        ),
    ]
