# Generated by Django 4.0.5 on 2022-06-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_principal_remove_post_foto_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_principal',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='post_imagens/%Y/%m/%d', verbose_name='Imagem Principal'),
        ),
    ]
