# Generated by Django 4.0.5 on 2022-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_foto_alter_post_principal_foto_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='post_principal',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Imagem Principal'),
        ),
    ]
