# Generated by Django 4.0.5 on 2022-06-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_principal_conteudo_post_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_post', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='post_principal',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_princical', verbose_name='Imagem Principal'),
        ),
    ]
