# Generated by Django 4.0.5 on 2022-06-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_principal_foto_principal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_principal',
        ),
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_post/%Y/%m/%d', verbose_name='Imagem'),
        ),
    ]
