# Generated by Django 4.0.5 on 2022-06-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='post_imagens_principal', verbose_name='Imagem Principal')),
                ('texto_principal', models.TextField(verbose_name='Texto Principal')),
            ],
        ),
    ]
