# Generated by Django 4.0.5 on 2022-06-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenprincipal',
            old_name='imagem_principal',
            new_name='imagem_principais',
        ),
    ]
