# Generated by Django 4.0.5 on 2022-06-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_rename_imagem_principal_imagenprincipal_imagem_principais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenprincipal',
            old_name='imagem_principais',
            new_name='foto',
        ),
    ]
